### ISSUE TITLE
Plugin status is Broken

### ISSUE THREAD

**Issue by luzrain** [aholkner/matomo-cloudflare-location-provider#1]
It does not work. Checkbox is inactive and when I trying to delete, I have this error.

![1](https://user-images.githubusercontent.com/25800964/58386214-eadbab00-8004-11e9-8a69-64c55f2c59cd.PNG)
![2](https://user-images.githubusercontent.com/25800964/58386215-eadbab00-8004-11e9-886e-af278a3bd343.PNG)

**Comment by aholkner** [comment]
Thanks for the report.  The deactivation issue has been fixed in release 0.1.2.

The most likely cause of the plugin appearing "broken", is that you do not have the `HTTP_CF_IPCOUNTRY` header available.   You need to explicitly enable this option in the Cloudflare "Network" dashboard.  If you have done this and it's still broken, check that your web server is actually passing through the variable to PHP (Apache does this automatically, but other web servers may vary).
